=== B-O-A-J-P/Proyecto-Kings-League/LenguajeDeMarcas/Calendario_kings_league.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="temporada"/>
  
    <xs:complexType name="temporada">
      <xs:sequence>
        <xs:element name="split" type="Tiposplit" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Tiposplit">
      <xs:sequence>
        <xs:element name="jornada" type="Tipojornada" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="hora_inicio" type="xs:string"/>
        <xs:element name="hora_fin" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Tipojornada">
      <xs:sequence>
        <xs:element name="partido" type="Tipopartido" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="fecha" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>    
      
    <xs:complexType name="Tipopartido">
      <xs:sequence>
        <xs:element name="equipo" type="Tipoequipo" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="hora" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
    
    
        <xs:complexType name="Tipoequipo">
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="logo" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
    
    
</xs:schema>

=== B-O-A-J-P/Proyecto-Kings-League/LenguajeDeMarcas/Calendario_kings_league.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE temporada SYSTEM "Calendario_kings_league.dtd">
<temporada id="aa1"
xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "Calendario_kings_League.xsd">
  <split id="aa2">
  <hora_inicio></hora_inicio>
  <hora_fin></hora_fin>
    <jornada id="aa3">
    <fecha></fecha>
      <partido id="aa4" >
      <hora></hora>
          <equipo id="aa5">          
          <logo></logo>    
          <nombre></nombre>
          </equipo>      

          <equipo id="aa6">
           <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="aa7" >
        <hora></hora>
          <equipo id="aa8">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="aa9">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a10" >
       <hora></hora>
          <equipo id="a11">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a12">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a13" >
       <hora></hora>
          <equipo id="a14">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a15">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a16" >
       <hora></hora>
          <equipo id="a17">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a18">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a19" >
       <hora></hora>
          <equipo id="a20">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a21">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
    </jornada>
    
   <jornada id="a22">
       <fecha></fecha>
           <partido id="a23" >
            <hora></hora>
          <equipo id="a24">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a25">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a26" >
       <hora></hora>
          <equipo id="a27">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a28">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a29" >
       <hora></hora>
          <equipo id="a30">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a31">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a32" >
       <hora></hora>
          <equipo id="a33">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a34">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a35" >
       <hora></hora>
          <equipo id="a36">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a37">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a38" >
       <hora></hora>
          <equipo id="a39">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a40">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
    </jornada>
    
   <jornada id="a41">
       <fecha></fecha>
          <partido id="a42" >
           <hora></hora>
          <equipo id="a43">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a44">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a45" >
       <hora></hora>
          <equipo id="a46">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a47">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a49" >
       <hora></hora>
          <equipo id="a50">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a51">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a52" >
       <hora></hora>
          <equipo id="a53">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a54">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a55" >
       <hora></hora>
          <equipo id="a56">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a57">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a58" >
       <hora></hora>
          <equipo id="a59">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a60">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
    </jornada>
    
   <jornada id="a61">
        <fecha></fecha>
           <partido id="a62" >
           <hora></hora>
          <equipo id="a63">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a64">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a65" >
       <hora></hora>
          <equipo id="a66">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a67">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a68" >
       <hora></hora>
          <equipo id="a69">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a70">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a71" >
       <hora></hora>
          <equipo id="a72">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a73">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a74" >
       <hora></hora>
          <equipo id="a75">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a76">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a77" >
       <hora></hora>
          <equipo id="a78">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a79">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
    </jornada>
    
   <jornada id="a80">
       <fecha></fecha>
           <partido id="a81" >
            <hora></hora>
          <equipo id="a82">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a83">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a84" >
       <hora></hora>
          <equipo id="a85">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a86">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a87" >
       <hora></hora>
          <equipo id="a88">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a89">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a90" >
       <hora></hora>
          <equipo id="a91">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a92">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a93" >
       <hora></hora>
          <equipo id="a94">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a95">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
      
      <partido id="a96" >
       <hora></hora>
          <equipo id="a97">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
          <equipo id="a98">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
          
      </partido>
    </jornada>
    
   <jornada id="a99">
       <fecha></fecha>
      <partido id="a100" >
       <hora></hora>
          <equipo id="a101">
          	 <logo></logo>    
          <nombre></nombre>
          </equipo>
