=== B-O-A-J-P/Proyecto-Kings-League/LenguajeDeMarcas/kings_league_resultados_cada_jornada.dtd
<!ELEMENT split (jornada+)>
<!ELEMENT jornada  (partido+)>
<!ELEMENT partido (fecha_partido, equipo+)>
<!ELEMENT equipo (nombre,logo,numero_goles,resultado) >
<!ELEMENT fecha_partido (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT numero_goles (#PCDATA)>
<!ELEMENT resultado (#PCDATA)>


<!ATTLIST split id  ID #REQUIRED>
<!ATTLIST jornada id ID #REQUIRED>
<!ATTLIST partido id  ID #REQUIRED>
<!ATTLIST equipo id  ID #REQUIRED>

=== B-O-A-J-P/Proyecto-Kings-League/LenguajeDeMarcas/kings_league_resultados_cada_jornada.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE split SYSTEM "kings_league_resultados_cada_jornada.dtd">
<split id="s1" xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "kings_league_resultados_cada_jornada.xsd">
<jornada id="j1">
<partido id="a1">
<fecha_partido></fecha_partido>
<equipo id="aa1">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="aa2">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="a2">
<fecha_partido></fecha_partido>
<equipo id="aa3">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="aa4">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="a3">
<fecha_partido></fecha_partido>
<equipo id="aa5">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="aa6">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>


<partido id="a4">
<fecha_partido></fecha_partido>
<equipo id="aa7">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="aa8">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="a5">
<fecha_partido></fecha_partido>
<equipo id="aa9">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="aa10">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="a6">
<fecha_partido></fecha_partido>
<equipo id="aa11">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="aa12">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>


</jornada>

<jornada id="j2">
<partido id="b1">
<fecha_partido></fecha_partido>
<equipo id="bb1">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="bb2">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="b2">
<fecha_partido></fecha_partido>
<equipo id="bb3">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="bb4">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="b3">
<fecha_partido></fecha_partido>
<equipo id="bb5">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="bb6">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="b4">
<fecha_partido></fecha_partido>
<equipo id="bb7">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="bb8">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="b5">
<fecha_partido></fecha_partido>
<equipo id="bb9">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="bb10">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="b6">
<fecha_partido></fecha_partido>
<equipo id="bb11">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="bb12">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>


</jornada>

<jornada id="j3">
<partido id="c1">
<fecha_partido></fecha_partido>
<equipo id="cc1">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="cc2">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="c2">
<fecha_partido></fecha_partido>
<equipo id="cc3">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="cc4">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="c3">
<fecha_partido></fecha_partido>
<equipo id="cc5">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="cc6">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="c4">
<fecha_partido></fecha_partido>
<equipo id="cc7">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="cc8">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="c5">
<fecha_partido></fecha_partido>
<equipo id="cc9">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="cc10">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="c6">
<fecha_partido></fecha_partido>
<equipo id="cc11">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="cc12">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

</jornada>

<jornada id="j4">
<partido id="d1">
<fecha_partido></fecha_partido>
<equipo id="dd1">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="dd2">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="d2">
<fecha_partido></fecha_partido>
<equipo id="dd3">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="dd4">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="d3">
<fecha_partido></fecha_partido>
<equipo id="dd5">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="dd6">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="d4">
<fecha_partido></fecha_partido>
<equipo id="dd7">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="dd8">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="d5">
<fecha_partido></fecha_partido>
<equipo id="dd9">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="dd10">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="d6">
<fecha_partido></fecha_partido>
<equipo id="dd11">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="dd12">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

</jornada>

<jornada id="j5">
<partido id="f1">
<fecha_partido></fecha_partido>
<equipo id="ff1">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="ff2">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="f2">
<fecha_partido></fecha_partido>
<equipo id="ff3">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="ff4">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="f3">
<fecha_partido></fecha_partido>
<equipo id="ff5">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="ff6">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="f4">
<fecha_partido></fecha_partido>
<equipo id="ff7">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="ff8">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="f5">
<fecha_partido></fecha_partido>
<equipo id="ff9">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="ff10">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="f6">
<fecha_partido></fecha_partido>
<equipo id="ff11">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="ff12">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

</jornada>

<jornada id="j6">
<partido id="g1">
<fecha_partido></fecha_partido>
<equipo id="gg1">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="gg2">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="g2">
<fecha_partido></fecha_partido>
<equipo id="gg3">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="gg4">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>
</partido>

<partido id="g3">
<fecha_partido></fecha_partido>
<equipo id="gg5">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
<resultado></resultado>
</equipo>

<equipo id="gg6">
<nombre></nombre>
<logo></logo>
<numero_goles></numero_goles>
