=== B-O-A-J-P/Proyecto-Kings-League/LenguajeDeMarcas/kings_league_clasificacion.dtd
<!ELEMENT temporada (split)>
<!ELEMENT split  (clasificacion)>
<!ELEMENT clasificacion (equipo+,fecha_fin)>
<!ELEMENT equipo (nombre,logo,puntos,suma_goles) >
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT puntos (#PCDATA)>
<!ELEMENT suma_goles (#PCDATA)>
<!ELEMENT fecha_fin (#PCDATA)>


<!ATTLIST temporada id  ID #REQUIRED>
<!ATTLIST split id ID #REQUIRED>
<!ATTLIST equipo id  ID #REQUIRED>

=== B-O-A-J-P/Proyecto-Kings-League/LenguajeDeMarcas/kings_league_clasificacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE temporada SYSTEM "kings_league_clasificacion.dtd">
<temporada id ="a1" xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "kings_league_clasificacion.xsd">
<split id="b1">
<clasificacion>
<fecha_fin></fecha_fin>

<equipo id="eq1">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq2">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq3">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq4">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq5">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq6">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq7">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq8">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq9">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq10">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq11">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>

<equipo id="eq12">
<nombre></nombre>
<logo></logo>
<puntos></puntos>
<suma_goles></suma_goles>
</equipo>


</clasificacion>
</split>
</temporada>
